# Replace the text below to customize your site
site_name: Andrea Arranz 
site_description: Master in Design for Emergent Futures
site_author: Andrea
copyright: Copyleft 2021 "Andrea" - GNU Free Documentation License
repo_name: 'Name : Github Repo'
site_url: https://andrea-arranz.github.io/website/
repo_url: 'https://github.com/andrea-arranz/website'

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/andreaarranzsanchez/


theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: white
    accent: orange
  font:
    # See available fonts at https://fonts.google.com/
    text: Roboto
    code: IBM Plex Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - navigation.tabs

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
